name: KDTS CI

on:
  push:
    branches: [ kdts ]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [ kdts ]
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/run_tests.yaml
    with:
      ref: ${{ github.sha }}
